version: "3"
services:
  db-server:
    container_name: sample-mysql
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: sample
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: admin
    volumes:
      - ./docker/mysql/initdb:/docker-entrypoint-initdb.d
      - ./docker/mysql/config:/etc/mysql/conf.d
      - mysql_db:/var/lib/mysql
    ports:
      - "13306:3306"
  schemaspy:
    image: schemaspy/schemaspy
    depends_on:
      - db-server
    container_name: schemaspy
    volumes:
      - ./docker/schemaspy/output:/output
      - ./docker/schemaspy/config:/config
    command: [ "-configFile", "/config/schemaspy.properties" ]

  schemaspy-server:
    image: nginx
    depends_on:
      - schemaspy
    container_name: "nginx_for_schemaspy"
    ports:
      - "8181:80"
    volumes:
      - ./docker/schemaspy/output:/usr/share/nginx/html:ro

  app-server:
    container_name: sample-thymeleaf-todo
    image: sample-thymeleaf-todo:0.0.1-SNAPSHOT
    depends_on:
      - db-server
    ports:
      - "8080:8080"
    environment:
      spring.datasource.driver-class-name: "com.mysql.cj.jdbc.Driver"
      spring.datasource.url: "jdbc:mysql://db-server/sample"
      spring.datasource.username: "user"
      spring.datasource.password: "password"
volumes:
  mysql_db:
    driver: local
